version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: 'unless-stopped'
    ports:
      - '8096:8096'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - ./media2:/media2:ro
